#!/usr/bin/env node
// Generate index.html from decks.json + the deck files themselves.
//
// The split matters: decks.json holds only what a human decides (order, accent,
// blurb). Everything a machine can read off the deck — slide count, which
// languages it has, its <title>, its build stamp — is derived here, so the
// index can never disagree with the decks it links to.
//
// Adding a deck: write the HTML, add one entry to decks.json, run ./build.sh.
import fs from 'fs';
import path from 'path';

const ROOT = path.dirname(new URL(import.meta.url).pathname);
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'decks.json'), 'utf8'));

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// --- derive facts from each deck file, never from the registry -------------
function inspect(file) {
  const p = path.join(ROOT, file);
  if (!fs.existsSync(p)) throw new Error(`decks.json lists ${file}, which does not exist`);
  const s = fs.readFileSync(p, 'utf8');
  const slides = (s.match(/class="slide"/g) || []).length;
  if (!slides) throw new Error(`${file} has no .slide elements — wrong file?`);
  // a deck is bilingual if it carries Thai spans and a language switch
  const bilingual = /class="[^"]*\bth\b[^"]*"|lang-th/.test(s) && /btn-th|langsw/.test(s);
  const notes = /id="notes"/.test(s);
  const stamp = (s.match(/class="build"[^>]*>([^<]*)/) || [])[1] || null;
  const docTitle = (s.match(/<title>([^<]*)<\/title>/) || [])[1] || file;
  return { slides, bilingual, notes, stamp, docTitle };
}

const decks = cfg.decks.map(d => ({ ...d, ...inspect(d.file) }));

// --- the page -------------------------------------------------------------
const card = (d, i) => {
  const n = String(i + 1).padStart(2, '0');
  const langs = d.bilingual ? 'EN / ไทย' : 'EN';
  return `    <a class="deck ${d.accent}" href="${d.file}#${d.anchor}">
      <span class="n">${n} · ${d.slides} SLIDES · ${langs}</span>
      <h2 class="en">${esc(d.title.lead)} <b>${esc(d.title.accent)}</b></h2>
      <h2 class="th">${esc(d.titleTh.lead)}<b>${esc(d.titleTh.accent)}</b></h2>
      <p class="en">${esc(d.blurb.en)}</p>
      <p class="th">${esc(d.blurb.th)}</p>
      <span class="foot"><span class="en">${esc(d.foot.en)}</span><span class="th">${esc(d.foot.th)}</span><span class="go">open →</span></span>
    </a>`;
};

const fulls = decks.filter(d => d.full);
const fullsRow = fulls.length ? `
  <p class="fulls">
    <span class="en">Full versions, every source on the slide:</span><span class="th">เวอร์ชันละเอียด มีแหล่งอ้างอิงบนสไลด์:</span>
${fulls.map(d => `    <a href="${d.full}">${d.full.replace(/\.html$/, '')}</a>`).join('\n')}
  </p>
` : '';

const html = `<!doctype html>
<html lang="en" data-lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Workshop 2 — Build with Oracle</title>
<meta name="description" content="Slides for Build with Oracle, workshop 2: ${decks.map(d => esc(d.title.lead + ' ' + d.title.accent)).join(', ')}.">
<!-- GENERATED by build-index.mjs from decks.json — do not edit by hand. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&family=Noto+Sans+Thai:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{
  --ground:#eef0f3; --ink:#151a21; --text:#3a424d; --faint:#6b7480; --rule:#d5dae1;
  --dna:#6942a0; --dna-wash:#ede5f8;
  --prism:#4450b8; --prism-wash:#e6e8fa;
  --ma:#c2410c; --ma-wash:#fbe9e0;
  --sans:'Inter','Noto Sans Thai',system-ui,sans-serif; --serif:'Instrument Serif','Noto Sans Thai',Georgia,serif;
  --thai:'Noto Sans Thai','Inter',sans-serif; --mono:'JetBrains Mono',monospace;
}
@media (prefers-color-scheme: dark){
  :root{ --ground:#0f1318; --ink:#eef1f5; --text:#c3cad3; --faint:#8c96a3; --rule:#262d37;
         --dna:#c9a6f2; --dna-wash:#26193a;
         --prism:#a3abf5; --prism-wash:#1b2040;
         --ma:#fb8a3c; --ma-wash:#3a2214; }
}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--sans);font-size:18px;-webkit-font-smoothing:antialiased}
[data-lang="en"] .th{display:none!important}
[data-lang="th"] .en{display:none!important}
.th{font-family:var(--thai);font-weight:500}

main{max-width:960px;margin:0 auto;padding:clamp(40px,9vh,104px) clamp(20px,6vw,56px) 72px;display:flex;flex-direction:column;gap:40px}
header{display:flex;flex-direction:column;gap:16px}
.top{display:flex;align-items:center;gap:16px}
.tag{font-family:var(--mono);font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:var(--faint);margin:0;flex:1}
.langsw{display:flex;gap:2px;padding:2px;border:1px solid var(--rule);border-radius:5px}
.langsw button{font:inherit;font-family:var(--mono);font-size:12px;padding:5px 10px;border:0;border-radius:3px;background:none;color:var(--faint);cursor:pointer}
.langsw button[aria-pressed="true"]{background:var(--ink);color:var(--ground)}
h1{font-family:var(--serif);font-weight:400;font-size:clamp(3rem,9vw,6.4rem);line-height:.92;letter-spacing:-.02em;margin:0;text-wrap:balance}
h1.th{font-family:var(--thai);font-weight:600;font-size:clamp(2.3rem,7vw,4.8rem);line-height:1.25;letter-spacing:0}
.lede{font-size:clamp(1.1rem,2vw,1.35rem);line-height:1.55;color:var(--text);margin:0;max-width:44ch;text-wrap:pretty}
.lede.th{line-height:1.8}

/* three objects — the accent colour IS the card */
.decks{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}
.deck{--c:var(--dna);--w:var(--dna-wash);display:flex;flex-direction:column;gap:14px;padding:26px 24px 22px;border-radius:10px;background:var(--w);color:var(--ink);text-decoration:none;min-height:300px;position:relative;transition:transform 160ms,box-shadow 160ms}
.deck.prism{--c:var(--prism);--w:var(--prism-wash)}
.deck.ma{--c:var(--ma);--w:var(--ma-wash)}
.deck:hover{transform:translateY(-3px);box-shadow:0 14px 34px rgba(0,0,0,.12)}
.deck:focus-visible{outline:3px solid var(--c);outline-offset:3px}
.deck .n{font-family:var(--mono);font-size:12px;letter-spacing:.14em;color:var(--c)}
.deck h2{font-family:var(--serif);font-weight:400;font-size:clamp(2rem,3.4vw,2.7rem);line-height:.98;letter-spacing:-.015em;margin:0;text-wrap:balance}
.deck h2 b{font-weight:400;color:var(--c)}
.deck h2.th{font-family:var(--thai);font-weight:600;font-size:clamp(1.5rem,2.6vw,2rem);line-height:1.3;letter-spacing:0}
.deck p{margin:0;color:var(--text);line-height:1.55;font-size:15.5px;flex:1}
.deck p.th{line-height:1.85}
.deck .foot{display:flex;align-items:center;justify-content:space-between;gap:10px;font-family:var(--mono);font-size:13px;color:var(--faint);padding-top:14px;border-top:1px solid color-mix(in srgb,var(--c) 22%,transparent)}
.deck .foot>span{white-space:nowrap}
.deck .go{color:var(--c);font-weight:500;transition:transform 160ms}
.deck:hover .go{transform:translateX(4px)}

/* secondary row: the full versions, as their own links — never nested */
.fulls{display:flex;flex-wrap:wrap;gap:8px 22px;font-family:var(--mono);font-size:13px;color:var(--faint);align-items:baseline}
.fulls span{margin-right:4px}
.fulls a{color:var(--text);text-decoration:underline;text-underline-offset:4px;text-decoration-color:var(--rule)}
.fulls a:hover{color:var(--ink);text-decoration-color:currentColor}

.keys{display:flex;flex-wrap:wrap;gap:10px 24px;font-family:var(--mono);font-size:13px;color:var(--faint);padding-top:22px;border-top:1px solid var(--rule)}
.keys b{color:var(--ink);font-weight:500;font-family:var(--mono)}
footer{font-family:var(--mono);font-size:12.5px;color:var(--faint);line-height:1.8}

@media (max-width:820px){.deck{min-height:0}}
@media (prefers-reduced-motion:reduce){.deck,.deck .go{transition:none}}
</style>
</head>
<body>
<main>
  <header>
    <div class="top">
      <p class="tag">${esc(cfg.site.eyebrow)}</p>
      <div class="langsw" role="group" aria-label="Language"><button id="btn-en" lang="en" aria-pressed="true">EN</button><button id="btn-th" lang="th" aria-pressed="false">ไทย</button></div>
    </div>
    <h1 class="en">${esc(cfg.site.title.en)}</h1>
    <h1 class="th">${esc(cfg.site.title.th)}</h1>
    <p class="lede en">${esc(cfg.site.lede.en)}</p>
    <p class="lede th">${esc(cfg.site.lede.th)}</p>
  </header>

  <nav class="decks" aria-label="Slide decks">
${decks.map(card).join('\n\n')}
  </nav>
${fullsRow}
  <div class="keys">
    <span><b>← →</b> <span class="en">slides</span><span class="th">เลื่อนสไลด์</span></span>
    <span><b>T</b> EN / ไทย</span>
    <span><b>N</b> <span class="en">presenter notes</span><span class="th">โน้ตผู้บรรยาย</span></span>
    <span><b>F</b> <span class="en">fullscreen</span><span class="th">เต็มจอ</span></span>
    <span><b>G</b> <span class="en">grid, full decks</span><span class="th">ตารางรวม เฉพาะเวอร์ชันละเอียด</span></span>
  </div>

  <footer><span class="en">Single-file HTML, no build step. Fonts from Google Fonts; everything else inline.</span><span class="th">HTML ไฟล์เดียว ไม่ต้อง build ฟอนต์จาก Google Fonts ที่เหลืออยู่ในไฟล์ทั้งหมด</span><br>Written with Claude Code · Soul Brews Studio · 2026-09</footer>
</main>
<script>
(() => {
  const root = document.documentElement, en = document.getElementById('btn-en'), th = document.getElementById('btn-th');
  let lang = 'en'; try { lang = localStorage.getItem('workshop2-lang') || 'en'; } catch (e) {}
  function set(l) {
    lang = l === 'th' ? 'th' : 'en';
    root.setAttribute('data-lang', lang); root.lang = lang;
    en.setAttribute('aria-pressed', String(lang === 'en')); th.setAttribute('aria-pressed', String(lang === 'th'));
    try { localStorage.setItem('workshop2-lang', lang); } catch (e) {}
  }
  en.addEventListener('click', () => set('en')); th.addEventListener('click', () => set('th'));
  document.addEventListener('keydown', e => { if (!e.metaKey && !e.ctrlKey && !e.altKey && (e.key === 't' || e.key === 'T')) { e.preventDefault(); set(lang === 'en' ? 'th' : 'en'); } });
  set(lang);
})();
</script>
</body>
</html>
`;

fs.writeFileSync(path.join(ROOT, 'index.html'), html);

// --- machine-readable sidecar: sources, for anything that wants to collect --
const manifest = {
  generated: new Date().toISOString(),
  base: cfg.site.base,
  decks: decks.map(d => ({
    file: d.file,
    title: d.title.lead + ' ' + d.title.accent,
    slides: d.slides,
    languages: d.bilingual ? ['en', 'th'] : ['en'],
    notes: d.notes,
    build: d.stamp,
    anchor: d.anchor,
    url: cfg.site.base + d.file + '#' + d.anchor,
    local: 'file://' + path.join(ROOT, d.file) + '#' + d.anchor,
    full: d.full ? cfg.site.base + d.full : null,
  })),
};
fs.writeFileSync(path.join(ROOT, 'decks.manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

for (const d of decks) {
  console.log(`  ${d.file.padEnd(22)} ${String(d.slides).padStart(2)} slides  ${(d.bilingual ? 'en+th' : 'en').padEnd(5)}  notes:${d.notes ? 'y' : 'n'}  ${d.stamp || '(unstamped)'}`);
}
console.log(`  → index.html + decks.manifest.json  (${decks.length} decks)`);
